import 'package:code_db_1st/models/CI_ES_Collection/es_collection_data.dart';

class ESDB{
  List<ES_CData> getAllData(){
    List<ES_CData> data = [];
      ES_CData e1 = ES_CData("Animal (fish, bird,\nmammal etc)", "304 collections", "assets/ES_Collection/CoinIverse_ES_C/es1.jpg");
      data.add(e1);
      ES_CData e2 = ES_CData("Art (sculpture,\npainting etc)", "175 collections", "assets/ES_Collection/CoinIverse_ES_C/es2.jpg");
      data.add(e2);
      ES_CData e3 = ES_CData("Aviation &\nastronautics etc", "26 collections", "assets/ES_Collection/CoinIverse_ES_C/es3.jpg");
      data.add(e3);
      ES_CData e4 = ES_CData("Book", "48 collections", "assets/ES_Collection/CoinIverse_ES_C/es4.jpg");
      data.add(e4);
      ES_CData e5 = ES_CData("British royal family", "10 collections", "assets/ES_Collection/CoinIverse_ES_C/es1.jpg");
      data.add(e5);
      ES_CData e6 = ES_CData("Character (book, movie,cartoon etc)", "26 collections", "assets/ES_Collection/CoinIverse_ES_C/es2.jpg");
      data.add(e6);
      ES_CData e7 = ES_CData("Coat of arms", "272 collections", "assets/ES_Collection/CoinIverse_ES_C/es3.jpg");
      data.add(e7);
      ES_CData e8 = ES_CData("Coin, banknote", "20 collections", "assets/ES_Collection/CoinIverse_ES_C/es4.jpg");
      data.add(e8);
      ES_CData e9 = ES_CData("Construction\n(building, bridge tc...)", "209 collections", "assets/ES_Collection/CoinIverse_ES_C/es1.jpg");
      data.add(e9);
      ES_CData e10 = ES_CData("Costume (hat, dress,\netc.)", "22 collections", "assets/ES_Collection/CoinIverse_ES_C/es2.jpg");
      data.add(e10);
      ES_CData e11 = ES_CData("Crown, jewelry", "122 collections", "assets/ES_Collection/CoinIverse_ES_C/es3.jpg");
      data.add(e11);
      ES_CData e12 = ES_CData("Deity (god, goddess\netc.)", "55 collections", "assets/ES_Collection/CoinIverse_ES_C/es4.jpg");
      data.add(e12);
      ES_CData e13 = ES_CData("Device and tools\n(watch, compass, t...", "65 collections", "assets/ES_Collection/CoinIverse_ES_C/es1.jpg");
      data.add(e13);
      ES_CData e14 = ES_CData("Discovery, invention", "13 collections", "assets/ES_Collection/CoinIverse_ES_C/es2.jpg");
      data.add(e14);
      ES_CData e15 = ES_CData("flag", "108 collections", "assets/ES_Collection/CoinIverse_ES_C/es3.jpg");
      data.add(e15);
    ES_CData e16 = ES_CData("Food, drink", "4 collections", "assets/ES_Collection/CoinIverse_ES_C/es4.jpg");
    data.add(e16);
    ES_CData e17 = ES_CData("Fruit, berry,\nvegetable", "32 collections", "assets/ES_Collection/CoinIverse_ES_C/es1.jpg");
    data.add(e17);
    ES_CData e18 = ES_CData("Furniture & dishes", "18 collections", "assets/ES_Collection/CoinIverse_ES_C/es2.jpg");
    data.add(e18);
    ES_CData e19 = ES_CData("Geography &\nastronomy", "365 collections", "assets/ES_Collection/CoinIverse_ES_C/es3.jpg");
    data.add(e19);
    ES_CData e20 = ES_CData("Insect (butterfly,ant)\n& arachind (spider, ...", "11 collections", "assets/ES_Collection/CoinIverse_ES_C/es4.jpg");
    data.add(e20);
    ES_CData e21 = ES_CData("Legendary creature\n(dragon, unicorn et...", "39 collections", "assets/ES_Collection/CoinIverse_ES_C/es1.jpg");
    data.add(e21);
    ES_CData e22 = ES_CData("Military", "103 collections", "assets/ES_Collection/CoinIverse_ES_C/es2.jpg");
    data.add(e22);
    ES_CData e23 = ES_CData("Monogram,\nsignature", "98 collections", "assets/ES_Collection/CoinIverse_ES_C/es3.jpg");
    data.add(e23);
    ES_CData e24 = ES_CData("Music (Instrument,\nnotes etc.)", "67 collections", "assets/ES_Collection/CoinIverse_ES_C/es4.jpg");
    data.add(e24);
    ES_CData e25 = ES_CData("Nature (hill, river\netc.)", "79 collections", "assets/ES_Collection/CoinIverse_ES_C/es1.jpg");
    data.add(e25);
    ES_CData e26 = ES_CData("Navy (ship,\nsubmarine etc.)", "89 collections", "assets/ES_Collection/CoinIverse_ES_C/es2.jpg");
    data.add(e26);
    ES_CData e27 = ES_CData("Order, medal etc.", "25 collections", "assets/ES_Collection/CoinIverse_ES_C/es3.jpg");
    data.add(e27);
    ES_CData e28 = ES_CData("People (man,\nwoman, child etc.)", "106 collections", "assets/ES_Collection/CoinIverse_ES_C/es4.jpg");
    data.add(e28);
    ES_CData e29 = ES_CData("Person (actor\nmusician, painter e...", "41 collections", "assets/ES_Collection/CoinIverse_ES_C/es1.jpg");
    data.add(e29);
    ES_CData e30 = ES_CData("Person (king, queen,\ntsar etc.)", "221 collections", "assets/ES_Collection/CoinIverse_ES_C/es2.jpg");
    data.add(e30);
    ES_CData e31 = ES_CData("Person (military)", "18 collections", "assets/ES_Collection/CoinIverse_ES_C/es3.jpg");
    data.add(e31);
    ES_CData e32 = ES_CData("Person (politician,\nrevolutionary, entre...", "160 collections", "assets/ES_Collection/CoinIverse_ES_C/es4.jpg");
    data.add(e32);
    ES_CData e33 = ES_CData("Person (religious\nfigure)", "25 collections", "assets/ES_Collection/CoinIverse_ES_C/es1.jpg");
    data.add(e33);
    ES_CData e34 = ES_CData("Person (scientist,\ninventor, explorer e...", "16 collections", "assets/ES_Collection/CoinIverse_ES_C/es2.jpg");
    data.add(e34);
    ES_CData e35 = ES_CData("Person (sportsman)", "9 collections", "assets/ES_Collection/CoinIverse_ES_C/es3.jpg");
    data.add(e35);
    ES_CData e36 = ES_CData("Person (writer, poet,\nphilospher etc.)", "69 collections", "assets/ES_Collection/CoinIverse_ES_C/es4.jpg");
    data.add(e36);
    ES_CData e37 = ES_CData("Rider", "40 collections", "assets/ES_Collection/CoinIverse_ES_C/es1.jpg");
    data.add(e37);
    ES_CData e38 = ES_CData("Sports, Olympics", "64 collections", "assets/ES_Collection/CoinIverse_ES_C/es2.jpg");
    data.add(e38);
    ES_CData e39 = ES_CData("Stone, meteorite etc.", "11 collections", "assets/ES_Collection/CoinIverse_ES_C/es3.jpg");
    data.add(e39);
    ES_CData e40 = ES_CData("Symbol, amulet,\ntailsman", "242 collections", "assets/ES_Collection/CoinIverse_ES_C/es4.jpg");
    data.add(e40);
    ES_CData e41 = ES_CData("Temple (church,\nmosque, synagogu...", "87 collections", "assets/ES_Collection/CoinIverse_ES_C/es1.jpg");
    data.add(e41);
    ES_CData e42 = ES_CData("Toy", "12 collections", "assets/ES_Collection/CoinIverse_ES_C/es2.jpg");
    data.add(e42);
    ES_CData e43 = ES_CData("Train, steam\nlocomotive etc.", "12 collections", "assets/ES_Collection/CoinIverse_ES_C/es3.jpg");
    data.add(e43);
    ES_CData e44 = ES_CData("Transport (wagon,\nbike, car, truck, etc.)", "17 collections", "assets/ES_Collection/CoinIverse_ES_C/es4.jpg");
    data.add(e44);
    ES_CData e45 = ES_CData("Tree, flower, plant\netc", "248 collections", "assets/ES_Collection/CoinIverse_ES_C/es1.jpg");
    data.add(e45);
    ES_CData e46 = ES_CData("World War II", "8 collections", "assets/ES_Collection/CoinIverse_ES_C/es2.jpg");
    data.add(e46);
    ES_CData e47 = ES_CData("Zodiac", "1 collection", "assets/ES_Collection/CoinIverse_ES_C/es3.jpg");
    data.add(e47);
    return data;
  }
}